### ISSUE TITLE
Language files

### ISSUE THREAD

**Issue by LaoDong233** [quat1024/md18#10]
This is the Sinicization document I made for your module. Please look over it.
https://www.dropbox.com/s/pavd9ajkilux6ru/zh_cn.lang?dl=0

**Comment by quat1024** [comment]
Thank you, I really appreciate it!! :revolving_hearts: 

Can you also please translate this line?

    dazzle.tooltip.lamp=Use a Redstone Torch to invert

That's going to be a tooltip on all of the lamp items, when I finish the updated version.

Also - if you need me to switch the order of the color and style, in `tile.dazzle.digital_lamp.name` or `tile.dazzle.analog_lamp.name`, I can do that. I'm not familiar with Chinese so I don't know if putting the color before the style sounds weird?
