### ISSUE TITLE
[Suggestion] Have inverted versions of all your lights

### ISSUE THREAD

**Issue by mcdodge34** [quat1024/md18#3]
I mean by inverted that they don't need a redstone signal to be powered on, they would turn off on redstone signal if needed, about to design an aquatic base entrance where I want lights all around, but its hard to fiddle levers on each or redstone on all of them.

**Comment by towerofnix** [comment]
>they would turn off on redstone signal if needed

I would say "use a redstone torch", but I know that's not the point! :)

**Comment by quat1024** [comment]
Well lucky you, because right clicking with a redstone torch will invert them ;) There is no separate item.

I know this isn't explained very well anywhere; next update will add a tooltip.

**Comment by mcdodge34** [comment]
Great, this mod would need some kind of mod spotlight, I know its brand new, but it fit nicely with my builds at the moment, and what about the light sensor thingy, there's one already in Vanilla, maybe this one has something more...

**Comment by quat1024** [comment]
Yep, the light sensor detects block light, not sky light like the vanilla
one.

I could make a video/document it on the github wiki/add more tooltips when
i have some spare time

**Comment by mcdodge34** [comment]
Thanks, I feel like you are on a nice mod there, just need to be discovered by other people. And if I understand, none of your stuff can cause lag since they aren't tile entities right ???

**Comment by quat1024** [comment]
Maybe? I haven't done any profiling :P

Although it's a bit of a misconception that tile entities are *inherently*
bad for performance, and non-tiles are *inherently* good. It's true that
tile entities use a little more RAM per block, but I can do expensive
things in regular blocks too, e.g. I imagine the light panel is pretty
laggy, because it places lots and lots of invisible light source blocks.

The light sensor and dust lights are tiles btw.

**Comment by mcdodge34** [comment]
So that's what the light panel does, I have absolutely 0 description anywhere for all the stuff right now I use the sea lanterns, the white ones are amazing and much cheaper to craft than the real ones from Vanilla Minecraft, even if it needs that pesky prismarine crystal that are a little hard to farm, I plan on having an auto guardian farm soon enough so I'll swim in it.
