### ISSUE TITLE
Lights not coloured

### ISSUE THREAD

**Issue by SimulatorSia** [quat1024/md18#4]
All your lights look neat but none of them are coloured. You guys should take advantage of this core mod to give your lights a nicer arange of actual colours that display on other blocks.
https://minecraft.curseforge.com/projects/albedo

**Comment by quat1024** [comment]
The `postcompo` branch I'm working on already has rough support for Mirage (and its slightly worse cousin, Albedo) for the particle lights.

I thought it was impossible to implement on the non-particle lights, as they're not tile entities. mcenderdragon game me a hint I needed on reddit though. It's very hacky, but workable. Finishing up and testing the feature now before I push it

https://gfycat.com/SilkyImpishBunting

**Comment by quat1024** [comment]
Hey, it's like 1 million years later. I've decided not to implement this - it is far too messy and buggy for what it's worth, and it just doesn't look that good anyways. Especially if you overlap different color lights or stack too many.
